services:
  loki:
    image: grafana/loki:2.9.0
    command: -config.file=/etc/loki/config/config.yml
    ports:
      - "3100:3100"
    volumes:
      - ./loki-config.yml:/etc/loki/config/config.yml
      - ./loki-data:/loki

  promtail:
    image: grafana/promtail:2.9.0
    command: -config.file=/etc/promtail/config.yml
    volumes:
      - /var/log:/var/log:ro
      - ./promtail-config.yml:/etc/promtail/config.yml
    depends_on:
      - loki

  prometheus_shard1:
    image: prom/prometheus:v2.53.0
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus-shard1-data:/prometheus # TSDB folder for sidecar
      - ./prometheus1.yml:/etc/prometheus/prometheus.yml
      - ./rules:/etc/prometheus/rules
      - ./file_sd:/etc/prometheus/file_sd
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--web.enable-lifecycle"
      - "--storage.tsdb.min-block-duration=2h"
      - "--storage.tsdb.max-block-duration=2h"
    restart: unless-stopped

  prometheus_shard2:
    image: prom/prometheus:v2.53.0
    ports:
      - "9092:9090"
    volumes:
      - ./prometheus-shard2-data:/prometheus # TSDB folder for sidecar
      - ./prometheus2.yml:/etc/prometheus/prometheus.yml
      - ./rules:/etc/prometheus/rules
      - ./file_sd:/etc/prometheus/file_sd
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.path=/prometheus
      - --web.enable-lifecycle
      - --storage.tsdb.min-block-duration=2h
      - --storage.tsdb.max-block-duration=2h
    restart: unless-stopped

  node-exporter:
    image: prom/node-exporter:v1.8.2
    ports:
      - "9100:9100"
    depends_on:
      - prometheus_shard1
      - prometheus_shard2

  grafana1:
    image: grafana/grafana:10.0.0
    ports:
      - "3000:3000"
    volumes:
      - ./grafana-storage:/var/lib/grafana
      - ./grafana-config/grafana.ini:/etc/grafana/grafana.ini
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - loki
      - prometheus_shard1
      - prometheus_shard2

  grafana2:
    image: grafana/grafana:10.0.0
    ports:
      - "3001:3000"
    volumes:
      - ./grafana-storage:/var/lib/grafana
      - ./grafana-config/grafana.ini:/etc/grafana/grafana.ini
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - loki
      - prometheus_shard1
      - prometheus_shard2

  alertmanager:
    image: prom/alertmanager:v0.27.0
    ports:
      - "9093:9093"
    volumes:
      - ./alertmanager.yml:/etc/alertmanager/alertmanager.yml
    depends_on:
      - prometheus_shard1
      - prometheus_shard2

  myapp:
    build: ./app
    ports:
      - "8000:8000"
    depends_on:
      - prometheus_shard1
      - prometheus_shard2

  shoehubapp:
    image: aussiearef/shoehub:latest
    ports:
      - "8080:8080"
    depends_on:
      - prometheus_shard1
      - prometheus_shard2

  pushgateway:
    image: prom/pushgateway:v1.9.0
    container_name: pushgateway
    ports:
      - "9091:9091"

  push_job:
    build: ./app
    command: python push_job.py
    depends_on:
      - pushgateway
      - prometheus_shard1
      - prometheus_shard2

  # --------------------------
  # Thanos Sidecars
  # --------------------------
  thanos-sidecar1:
    image: thanosio/thanos:v0.30.0
    command:
      - sidecar
      - --prometheus.url=http://prometheus_shard1:9090
      - --tsdb.path=/prometheus
      - --objstore.config-file=/etc/thanos/bucket.yml
      - --http-address=0.0.0.0:10901
      - --grpc-address=0.0.0.0:10911 # different from HTTP
    depends_on:
      - prometheus_shard1
      - minio
    volumes:
      - ./prometheus-shard1-data:/prometheus
      - ./thanos-bucket.yml:/etc/thanos/bucket.yml
    ports:
      - "10901:10901" # HTTP
      - "10911:10911" # gRPC
    restart: unless-stopped

  thanos-sidecar2:
    image: thanosio/thanos:v0.30.0
    command:
      - sidecar
      - --prometheus.url=http://prometheus_shard2:9090
      - --tsdb.path=/prometheus
      - --objstore.config-file=/etc/thanos/bucket.yml
      - --http-address=0.0.0.0:10902
      - --grpc-address=0.0.0.0:10912 # different from HTTP
    depends_on:
      - prometheus_shard2
      - minio
    volumes:
      - ./prometheus-shard2-data:/prometheus
      - ./thanos-bucket.yml:/etc/thanos/bucket.yml
    ports:
      - "10902:10902" # HTTP
      - "10912:10912" # gRPC
    restart: unless-stopped

  thanos-query:
    image: thanosio/thanos:v0.30.0
    command:
      - query
      - --http-address=0.0.0.0:10905
      - --store=thanos-sidecar1:10911
      - --store=thanos-sidecar2:10912
    depends_on:
      - thanos-sidecar1
      - thanos-sidecar2
    ports:
      - "10905:10905"

  thanos-query-frontend:
    image: thanosio/thanos:v0.30.0
    command:
      - query-frontend
      - --http-address=0.0.0.0:10906
      - --query-frontend.downstream-url=http://thanos-query:10905
    depends_on:
      - thanos-query
    ports:
      - "10906:10906"

  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - ./minio-data:/data

volumes:
  grafana-storage:
