global:
  scrape_interval: 15s
  external_labels:
    cluster: shard1

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - alertmanager:9093

rule_files:
  - "/etc/prometheus/rules/alert.yaml"
  - "/etc/prometheus/rules/recording_rule.yaml"

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ["prometheus:9090"]

  - job_name: node-exporter
    static_configs:
      - targets: ["node-exporter:9100"]
    metric_relabel_configs:
      - source_labels: [__name__]
        regex: "node_cpu_seconds_total"
        action: drop

  - job_name: loki
    static_configs:
      - targets: ["loki:3100"]

  - job_name: myapp-discovery
    file_sd_configs:
      - files:
          - /etc/prometheus/file_sd/*.yml
        refresh_interval: 30s
